forge 'http://forge.puppetlabs.com'

## forge modules
mod 'abstractit/puppet', '1.7.7'

## OpenStack Modules
mod 'puppetlabs/openstack', '5.0.2'
mod 'stackforge/ceilometer', '5.0.0'
mod 'stackforge/cinder', '5.0.0'
mod 'stackforge/glance', '5.0.0'
mod 'stackforge/heat', '5.0.0'
mod 'stackforge/horizon', '5.0.0'
mod 'stackforge/keystone', '5.0.0'
mod 'stackforge/neutron', '5.0.0'
mod 'stackforge/nova', '5.0.0'
mod 'stackforge/swift', '5.0.0'
mod 'stackforge/tempest', '5.0.0'

mod 'stackforge/openstacklib', '5.0.0'
mod 'aimonb/aviator', '0.5.1'
mod 'puppetlabs/stdlib', '4.5.1'
mod 'puppetlabs/mysql', '2.3.1'
mod 'puppetlabs/rabbitmq', '3.0.0'
mod 'nanliu/staging', '1.0.3'
mod 'dprince/qpid', '1.0.2'
mod 'puppetlabs/inifile', '1.2.0'
mod 'puppetlabs/apache', '1.2.0'
mod 'puppetlabs/concat', '1.1.2'
mod 'saz/memcached', '2.6.0'
mod 'puppetlabs/firewall', '1.4.0'
mod 'stackforge/vswitch', '1.0.0'
mod 'duritong/sysctl', '0.0.1'
mod 'puppetlabs/rsync', '0.4.0'
mod 'puppetlabs/xinetd','1.4.0'
mod 'saz/ssh', '1.4.0'
mod 'puppetlabs/mongodb', '0.10.0'
mod 'puppetlabs/apt', '1.7.0'
mod 'puppetlabs/ntp', '3.3.0'
mod 'puppetlabs/vcsrepo', '1.2.0'
